### ISSUE TITLE
Cymetric has a dependency on cython

### ISSUE THREAD

**Issue by mbmcgarry** [cyclus/cymetric#105]
This is required to install cymetric but not listed in the dependencies and doesn't appear to be part of standard python distribution.

**Comment by opotowsky** [comment]
Whoops, pyne and its dependencies are considered optional, so cython definitely needs to be on the list. Thanks for catching this!

**Comment by scopatz** [comment]
This is no longer true since cymetric is now pure Python. Please feel free to close.
