### ISSUE TITLE
Cymetric/master not compile against cyclus/master + cycamore/master

### ISSUE THREAD

**Issue by Baaaaam** [cyclus/cymetric#108]
while trying to build cymetric build fails:

> Generating API Bindings...
> 
> --------------------
> 
> If you are having issues building cymetric, please report your problem to cyclus-dev@googlegroups.com or look for help at http://fuelcycle.org
> 
> --------------------
> Traceback (most recent call last):
>   File "setup.py", line 269, in <module>
>     main()
>   File "setup.py", line 240, in main
>     main_body(cmake_args, make_args)
>   File "setup.py", line 214, in main_body
>     genapi.main([])
>   File "/Users/mouginot/work/app/cyclus/cymetric/genapi.py", line 962, in main
>     code_gen(ts, ns)
>   File "/Users/mouginot/work/app/cyclus/cymetric/genapi.py", line 945, in code_gen
>     s = func(ts, ns)
>   File "/Users/mouginot/work/app/cyclus/cymetric/genapi.py", line 810, in typesystem_pyx
>     rtn = TYPESYSTEM_PYX.render(ctx)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
>     raise value.with_traceback(tb)
>   File "<template>", line 93, in top-level template code
>   File "/Users/mouginot/work/app/cyclus/cymetric/genapi.py", line 213, in convert_to_py
>     decl = decl.format(**ctx)
> KeyError: 'valdecl'

**Comment by Baaaaam** [comment]
I am using python 3.5 and MACOS

**Comment by scopatz** [comment]
Hi @Baaaaam, I can confirm that I fixed this in cyclus/cyclus#1309

**Comment by Baaaaam** [comment]
shall we merge cyclus/cyclus#1309 into a micro release ?

**Comment by scopatz** [comment]
Yeah it should probably go into a micro release. But once it is merged, cymetric will need to be updated, I don't know what the testings dependencies are like.  Does cyclus need to be in a micro release for cymetric CI to see the change?

**Comment by Baaaaam** [comment]
As cymetric test don't specify the cyclus-cycamore container version I believe they use the :latest version which is updated on develop merge.

We probably want:
- to be sure the fix fixes the issues there
- Cymetric and Cymetric test are working
- Cymetric:stable docker container uses cycamore:stable container
- then release a micro version for Cyclus/Cycamore/Cymetric

**Comment by scopatz** [comment]
Sounds good to me

**Comment by Baaaaam** [comment]
@scopatz it looks like I have almost the same issue:

> Generating API Bindings...
> 
> --------------------
> 
> If you are having issues building cymetric, please report your problem to cyclus-dev@googlegroups.com or look for help at http://fuelcycle.org
> 
> --------------------
> Traceback (most recent call last):
>   File "setup.py", line 269, in <module>
>     main()
>   File "setup.py", line 240, in main
>     main_body(cmake_args, make_args)
>   File "setup.py", line 214, in main_body
>     genapi.main([])
>   File "/home/mouginot/work/app/cyclus/cymetric/genapi.py", line 962, in main
>     code_gen(ts, ns)
>   File "/home/mouginot/work/app/cyclus/cymetric/genapi.py", line 945, in code_gen
>     s = func(ts, ns)
>   File "/home/mouginot/work/app/cyclus/cymetric/genapi.py", line 810, in typesystem_pyx
>     rtn = TYPESYSTEM_PYX.render(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "<template>", line 93, in top-level template code
>   File "/home/mouginot/work/app/cyclus/cymetric/genapi.py", line 213, in convert_to_py
>     decl = decl.format(**ctx)
> KeyError: u'valdecl'


the last line is different tho: 
> KeyError: 'valdecl'

vs

> KeyError: u'valdecl'

**Comment by Baaaaam** [comment]
the last line is different:

> KeyError: 'valdecl'

vs 

> KeyError: u'valdecl'

**Comment by scopatz** [comment]
That is a python 2 vs 3 difference

**Comment by Baaaaam** [comment]
just to be sure I recompile cyclus (develop + scopatz:py) cycamore (master) still have the same issue.

I am trying the same on ubuntu 16.10 + python 2.7

**Comment by scopatz** [comment]
Cymetric will need a PR to fix its issues after the cyclus/scopatz:py pr is merged.  It isn't enough on its own, but all the "hard" work is in that PR

**Comment by Baaaaam** [comment]
not sure if its helps but: If I revert my cyclus version before the update of `share/dbtypes.json.in` file (#da822b9) in cyclus,  it solve the pb.
But you might already know were it comes from....

**Comment by scopatz** [comment]
Yeah, both the typesystem and the dbtypes (in queryable backend) had bugs in them.  So yeah, if your revert far enough back, those extra types are no longer picked up.  I'll try to start fixing up cymetric to work on the new cyclus develop tonight / tomorrow.

**Comment by Baaaaam** [comment]
thx @scopatz!

don't hesitate to ping me if I can be of any help!

**Comment by scopatz** [comment]
will do :)

**Comment by Baaaaam** [comment]
this has been solve and included in 1.5.0. 
thx @scopatz
