### ISSUE TITLE
Develop a Jupyter notebook demonstrating the capabilities of Cymetric

### ISSUE THREAD

**Issue by FlanFlanagan** [cyclus/cymetric#134]
This is one of the todo items from the Cyclus meeting this summer. I think this is a great idea, and I think that @bam241 already has some of the functionality already completed? 

End goal is to get the notebook onto the website as an example for new and current cyclus users.

**Comment by katyhuff** [comment]
@bam241 It seems like this is now complete! Maybe it would be appropriate to link to the demo notebook repo from the cymetric readme, to close this issue?

**Comment by abachma2** [comment]
Closed with PR #173
