### ISSUE TITLE
CI Failing? Missing Dockerfile? 

### ISSUE THREAD

**Issue by katyhuff** [cyclus/cymetric#144]
I'm not sure what's happening here...
I merged #143 , which was passing all checks... but then got an email indicating things weren't as rosy as they seem.

I've not seen this docker error before, @bam241 ... Do you know what this is about?

https://circleci.com/gh/cyclus/cymetric/257?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by bam241** [comment]
it is because this step only occurs when merging, it updates the cymetric docker container on docker hub.
For some reason the generation of the docker container is failing...
