### ISSUE TITLE
Deprecation issues

### ISSUE THREAD

**Issue by abachma2** [cyclus/cymetric#186]
Because of updates across python, various parts of cymetric have been deprecated:
- using `python setup.py`, need to update README with new install isntructions, such as `pip install --target=$(cyclus --install-path)  .`
- the `MutableSequence` class in `collections`
- `imp` module, deprecated in favor of `importlib`

**Comment by nuclearkatie** [comment]
PR #185 tackles a couple of these, but not the install stuff
