### ISSUE TITLE
Move dbtypes.json into cymetric

### ISSUE THREAD

**Issue by scopatz** [cyclus/cymetric#49]
As the canonical home for the json file.  Right now it lives as a JSON string in the dbtypes.js file in the documentation repo at https://github.com/cyclus/cyclus.github.com/blob/source/source/arche/dbtypes.js  Just the `dbdata` variable needs to be stripped out and put in its own file here.  Then the downloading of this file during cymetric build can be removed.

**Comment by opotowsky** [comment]
@scopatz (and/or @gidden) I'm finally getting to this but not sure I fully understand. Do I copy the contents of the file over into cymetric? I snooped around and couldn't find where I would remove the downloading of the file from.

**Comment by scopatz** [comment]
This is @gidden's idea, so I'll let him explain.

**Comment by gidden** [comment]
we should probably revisit this w.r.t. https://groups.google.com/forum/#!topic/cyclus-dev/XRn5Qa-zWIA

**Comment by opotowsky** [comment]
closed with a different solution via https://github.com/cyclus/cymetric/pull/84
