### ISSUE TITLE
Cymetric Incompatible with Cyclus v1.3

### ISSUE THREAD

**Issue by opotowsky** [cyclus/cymetric#78]
UPDATE (5 Jun 2015)

A short and long term solution were both outlined for this issue. 

In the short term, PR https://github.com/cyclus/cymetric/pull/77 will be merged in. This allows Cymetric to build but renders it incompatible with the Cyclus/Cycamore 1.3 suite because it is using a stale dbtypes.js file. Updates to the entire suite require a near term micro-release so all repositories will be in sync. 

In the long term, we determined that the dbtypes.js file should live in Cyclus. Cymetric will then build off this file knowing the Cyclus path, and small changes will be made to genapi.py (already done here: https://github.com/gidden/cymetric/tree/testing) to accomodate the deletion of the first two columns. The website will have to be updated for this, and the bug in cymetric's type system generation (see (2) below) will have to be determined. 

----------------------------------

Cymetric downloads the dbtypes.js file from the website to get its type information in genapi.py. The recent changes to fuelcycle.org to the DbTypes table broke the Cymetric build. Two things were done: (1) two columns (Id and Name) were removed and (2) some complicated data types were added to enable recycle scenarios with the growth region. @gidden (https://github.com/gidden/cymetric/tree/testing) determined that even if the genapi.py file is fixed to address (1), that (2) still causes the Cymetric build to fail. Since (1) is not the issue (and I will show below that (2) is), the quick fix in https://github.com/cyclus/cymetric/pull/77 just has Cymetric build off the "old" DbTyles table without changing genapi.py. The next step is to refactor Cymetric somehow to not break with the new datatypes.

Onto the errors...

(1) Initial error: 

- Cymetric pulls the current dbtypes.js file from the website
```
DBTYPES_JS_URL = 'http://fuelcycle.org/arche/dbtypes.js'
```
- Build fails because genapi.py is looking for missing columns. 
```
~/cyclus/cymetric (develop) $ ./setup.py install --user
Generating API Bindings...

--------------------

If you are having issues building cymetric, please report your problem to cyclus-dev@googlegroups.com or look for help at http://fuelcycle.org

--------------------
Traceback (most recent call last):
  File "./setup.py", line 269, in <module>
    main()
  File "./setup.py", line 240, in main
    main_body(cmake_args, make_args)
  File "./setup.py", line 214, in main_body
    genapi.main([])
  File "/home/opotowsky/cyclus/cymetric/genapi.py", line 969, in main
    ts = setup(ns)
  File "/home/opotowsky/cyclus/cymetric/genapi.py", line 943, in setup
    cpp_typesystem=os.path.splitext(ns.cpp_typesystem)[0])
  File "/home/opotowsky/cyclus/cymetric/genapi.py", line 72, in __init__
    id, name, version = cols['id'], cols['name'], cols['version']
KeyError: u'id'
```

(2) Add back in missing columns, keeping new data type: still fails, instead because of the data type.

- Cymetric pulls a dbtypes.js file from https://github.com/gidden/cyclus.github.com/tree/testing
```
DBTYPES_JS_URL = 'https://raw.githubusercontent.com/gidden/cyclus.github.com/testing/source/arche/dbtypes.js'
```
- Build fails. 
```
~/cyclus/cymetric (develop) $ ./setup.py install --user
Generating API Bindings...
Downloading https://raw.githubusercontent.com/gidden/cyclus.github.com/testing/source/arche/dbtypes.js ...

--------------------

If you are having issues building cymetric, please report your problem to cyclus-dev@googlegroups.com or look for help at http://fuelcycle.org

--------------------
Traceback (most recent call last):
  File "./setup.py", line 269, in <module>
    main()
  File "./setup.py", line 240, in main
    main_body(cmake_args, make_args)
  File "./setup.py", line 214, in main_body
    genapi.main([])
  File "/home/opotowsky/cyclus/cymetric/genapi.py", line 970, in main
    code_gen(ts, ns)
  File "/home/opotowsky/cyclus/cymetric/genapi.py", line 953, in code_gen
    s = func(ts, ns)
  File "/home/opotowsky/cyclus/cymetric/genapi.py", line 810, in typesystem_pyx
    rtn = TYPESYSTEM_PYX.render(ctx)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 93, in top-level template code
  File "/home/opotowsky/cyclus/cymetric/genapi.py", line 213, in convert_to_py
    decl = decl.format(**ctx)
KeyError: u'valdecl'
```

(3) Add back in missing columns, remove new data type: passes.

- Cymetric pulls a dbtypes.js file from https://github.com/gidden/cyclus.github.com/tree/testing
```
DBTYPES_JS_URL = 'https://raw.githubusercontent.com/cyclus/cyclus.github.com/355dfbec0b408e7aa4b00bd673affc65b7c9090d/source/arche/dbtypes.js'
```
- Build passes

**Comment by gidden** [comment]
note that #80 fixes 1) and provides more information about 2)

**Comment by rwcarlsen** [comment]
Can you give a status update on this @opotowsky - has it been resolved?

**Comment by opotowsky** [comment]
https://github.com/cyclus/cymetric/pull/84/files fixed the compatibility issue but I'm trying to figure out what happened last summer to fix the data type problem. 

Cymetric builds fine but can't handle the data type added for the growth region in 1.3. https://gist.github.com/opotowsky/28a6761ed4ac97b2c555f962cbb95ab3

I think I should make a new, more specific issue and we can consider this one closed. Although the title works, this issue was mainly about cymetric building properly, which we have resolved

**Comment by opotowsky** [comment]
Closed via https://github.com/cyclus/cyclus/pull/1184 and https://github.com/cyclus/cymetric/pull/84
