### ISSUE TITLE
Cymetric should include a sample database

### ISSUE THREAD

**Issue by mbmcgarry** [cyclus/cymetric#87]
Please add a sample database and a relevant command that can be used to determine whether cymetric is correctly installed.

**Comment by opotowsky** [comment]
This is also something to be added to the documentation, but when you finish installing cymetric, run `nosetests` (either in the test directory or out of it by using `nosetests -w /path/cymetric/tests/`

**Comment by opotowsky** [comment]
I didn't fully answer this. 

There are test databases once nosetests runs successfully

**Comment by opotowsky** [comment]
Fixed via https://github.com/cyclus/cymetric/pull/94
